// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxuNcRLln9y1LaPppi2hd3fi7NBR48uqs',
    appId: '1:973211584327:web:c1cc3bda797e8fc4482e62',
    messagingSenderId: '973211584327',
    projectId: 'hrmsclone',
    authDomain: 'hrmsclone.firebaseapp.com',
    storageBucket: 'hrmsclone.firebasestorage.app',
    measurementId: 'G-NE8CSPMZRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8sV_DlcOqWyzLZH6Zap6FHRLFBP0I3Q',
    appId: '1:973211584327:android:6b14b07f6518cd72482e62',
    messagingSenderId: '973211584327',
    projectId: 'hrmsclone',
    storageBucket: 'hrmsclone.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTV6Jkofude2sayIutKModX91G5Uk7qxA',
    appId: '1:973211584327:ios:8344ffc40b4bf8b7482e62',
    messagingSenderId: '973211584327',
    projectId: 'hrmsclone',
    storageBucket: 'hrmsclone.firebasestorage.app',
    iosBundleId: 'com.example.hrmsClone',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTV6Jkofude2sayIutKModX91G5Uk7qxA',
    appId: '1:973211584327:ios:8344ffc40b4bf8b7482e62',
    messagingSenderId: '973211584327',
    projectId: 'hrmsclone',
    storageBucket: 'hrmsclone.firebasestorage.app',
    iosBundleId: 'com.example.hrmsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxuNcRLln9y1LaPppi2hd3fi7NBR48uqs',
    appId: '1:973211584327:web:83c05db49d8431ac482e62',
    messagingSenderId: '973211584327',
    projectId: 'hrmsclone',
    authDomain: 'hrmsclone.firebaseapp.com',
    storageBucket: 'hrmsclone.firebasestorage.app',
    measurementId: 'G-04XQN6BXM2',
  );
}
